name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  flatpak:
    name: "Flatpak"
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: morse.flatpak
          manifest-path: build-aux/io.teacond.Morse.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.variant.arch }}
          verbose: true
  
  windows:
    name: Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        include:
          - sys: clang64
            env: clang-x86_64
            arch: x64
          - sys: clangarm64
            env: clang-aarch64
            arch: arm64
    steps:
      - uses: actions/checkout@v6
      - name: "Setup MSYS2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            base-devel git mingw-w64-${{matrix.env}}-toolchain mingw-w64-${{matrix.env}}-cc
            mingw-w64-${{matrix.env}}-meson mingw-w64-${{matrix.env}}-ninja
            mingw-w64-${{matrix.env}}-pkg-config mingw-w64-${{matrix.env}}-ca-certificates
            mingw-w64-${{matrix.env}}-shaderc mingw-w64-${{matrix.env}}-curl
            mingw-w64-${{matrix.env}}-cmake mingw-w64-${{matrix.env}}-libxml2
            mingw-w64-${{matrix.env}}-gettext mingw-w64-${{matrix.env}}-vulkan
            mingw-w64-${{matrix.env}}-vulkan-headers mingw-w64-${{matrix.env}}-rust
            mingw-w64-${{matrix.env}}-python mingw-w64-${{matrix.env}}-python-pip
            mingw-w64-${{matrix.env}}-appstream mingw-w64-${{matrix.env}}-glib2
            mingw-w64-${{matrix.env}}-ccache mingw-w64-${{matrix.env}}-gobject-introspection
            mingw-w64-${{matrix.env}}-cairo mingw-w64-${{matrix.env}}-directx-headers
            mingw-w64-${{matrix.env}}-gdk-pixbuf2 mingw-w64-${{matrix.env}}-graphene
            mingw-w64-${{matrix.env}}-json-glib mingw-w64-${{matrix.env}}-libepoxy
            mingw-w64-${{matrix.env}}-fribidi mingw-w64-${{matrix.env}}-gst-plugins-bad-libs
            mingw-w64-${{matrix.env}}-shared-mime-info mingw-w64-${{matrix.env}}-python-gobject
            mingw-w64-${{matrix.env}}-sassc mingw-w64-${{matrix.env}}-pango
            mingw-w64-${{matrix.env}}-blueprint-compiler mingw-w64-${{matrix.env}}-python-setuptools
      - name: "Download Dependency Sources"
        run: |
          git clone https://gitlab.gnome.org/GNOME/gtk --depth 1
          git clone https://gitlab.gnome.org/GNOME/libadwaita --depth 1
      - name: Build Dependencies
        run: |
          export CC=clang
          export CXX=clang++
          cd gtk
          meson setup build -Dprefix=/clang64 -Dintrospection=enabled -Dmedia-gstreamer=disabled -Dbuild-tests=false -Dvulkan=enabled -Dsysprof=disabled -Dwin32-backend=true -Dx11-backend=false -Dwayland-backend=false
          meson install -C build
          cd ../
          cd libadwaita
          meson setup build -Dprefix=/clang64 -Dintrospection=enabled -Dvapi=false -Ddocumentation=false -Dtests=false
          meson install -C build
          cd ../
      - name: Build Package
        run: |
          meson setup build -Dprefix=$(pwd)/dist -Dprofile=default
          meson install -C build
          ldd dist/bin/morse.exe | grep /clang64/bin | cp $(awk '{print $3}') dist/bin
          cp /clang64/bin/gdbus.exe dist/bin
          mkdir -p dist/lib/gdk-pixbuf-2.0
          cp -r /clang64/lib/gdk-pixbuf-2.0/* dist/lib/gdk-pixbuf-2.0
      - name: Build Installer
        shell: powershell
        run: |
          iscc /DCPUType=${{matrix.arch}} build-aux/morse_inno.iss
      - uses: actions/upload-artifact@v6
        with:
          name: Morse_Installer_${{matrix.arch}}
          path: Output/*.exe