name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  flatpak:
    name: "Flatpak"
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{matrix.variant.runner}}
    steps:
      - uses: actions/checkout@v6
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: morse-${{matrix.variant.arch}}.flatpak
          manifest-path: build-aux/io.github.teacond.Morse.Devel.json
          cache-key: flatpak-builder-${{github.sha}}
          arch: ${{matrix.variant.arch}}
          verbose: true
          upload-artifact: false
      - uses: actions/upload-artifact@v6
        with:
          name: morse-${{matrix.variant.arch}}.flatpak
          path: morse-${{matrix.variant.arch}}.flatpak
  windows:
    name: Windows
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        include:
          - sys: clang64
            env: clang-x86_64
            runner: windows-latest
            arch: x64
          - sys: clangarm64
            env: clang-aarch64
            runner: windows-11-arm
            arch: arm64
    runs-on: ${{matrix.runner}}
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v6
      - name: "Setup MSYS2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            mingw-w64-${{matrix.env}}-git mingw-w64-${{matrix.env}}-meson
            mingw-w64-${{matrix.env}}-gettext mingw-w64-${{matrix.env}}-rust
            mingw-w64-${{matrix.env}}-gtk4 mingw-w64-${{matrix.env}}-libadwaita
            mingw-w64-${{matrix.env}}-blueprint-compiler
      - name: Build Package
        run: |
          meson setup build -Dprefix=$(pwd)/dist -Dprofile=default
          meson install -C build
          ldd dist/bin/morse.exe | grep /${{matrix.sys}}/bin | cp $(awk '{print $3}') dist/bin
          cp /${{matrix.sys}}/bin/gdbus.exe dist/bin
          mkdir -p dist/lib/gdk-pixbuf-2.0
          cp -r /${{matrix.sys}}/lib/gdk-pixbuf-2.0/* dist/lib/gdk-pixbuf-2.0
      - name: Build Installer
        shell: powershell
        run: |
          iscc /DCPUType=${{matrix.arch}} build-aux/morse_inno.iss
      - uses: actions/upload-artifact@v6
        with:
          name: morse-win-installer-${{matrix.arch}}.exe
          path: Output/*.exe
  macos:
    name: MacOS
    runs-on: macos-26
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v6
      - name: "Install System Packages"
        run: |
          brew update
          brew install meson gettext rust gtk4 libadwaita blueprint-compiler create-dmg dylibbundler librsvg
      - name: Build Package
        run: |
          meson setup build -Dprefix=$(pwd)/Morse.app -Ddatadir=Contents/Resources -Dbindir=Contents/MacOS -Dlocaledir=Contents/Resources/locale -Dprofile=default
          meson install -C build
          dylibbundler -od -b -x Morse.app/Contents/MacOS/morse -d Morse.app/Contents/Frameworks/ -p @executable_path/../Frameworks/
          mkdir morse.iconset
          for size in 16 32 128 256 512; do
              rsvg-convert -w $size -h $size data/icons/hicolor/scalable/apps/io.github.teacond.Morse.svg -o morse.iconset/icon_${size}x${size}.png
              rsvg-convert -w $((size*2)) -h $((size*2)) data/icons/hicolor/scalable/apps/io.github.teacond.Morse.svg -o morse.iconset/icon_${size}x${size}@2x.png
          done
          iconutil -c icns morse.iconset
          cp morse.icns Morse.app/Contents/Resources
          cp build-aux/Info.plist Morse.app/Contents/Info.plist
      - name: Sign Package
        run: codesign --force --deep -s - Morse.app
      - name: Build Installer
        run: |
          create-dmg --volname "Morse Installer" --volicon "morse.icns" --window-pos 200 120 \
          --window-size 800 400 --icon-size 100 --icon "Morse.app" 200 190 --hide-extension "Morse.app" \
          --app-drop-link 600 185 --skip-jenkins "morse-macos-installer-arm64.dmg" "./Morse.app"
      - uses: actions/upload-artifact@v6
        with:
          name: morse-macos-installer-arm64.dmg
          path: morse-macos-installer-arm64.dmg
  debian:
    name: "Debian"
    continue-on-error: true
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: aarch64
    runs-on: ${{matrix.runner}}
    container: debian:sid
    steps:
      - uses: actions/checkout@v6
      - name: Build Package
        run: |
          apt update
          apt install -y debhelper devscripts
          apt build-dep -y .
          dpkg-buildpackage -b -uc -us
          mv ../morse-gtk_*.deb ./
      - uses: actions/upload-artifact@v6
        with:
          name: morse-${{matrix.arch}}.deb
          path: morse-gtk_*.deb
  publish:
    name: Publish Release
    needs: [flatpak, windows, macos, debian]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v7
        with:
          path: ./binaries
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./binaries/*
