name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  flatpak:
    name: "Flatpak"
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: morse.flatpak
          manifest-path: build-aux/io.teacond.Morse.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.variant.arch }}
          verbose: true
  
  windows:
    name: Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v6
      - name: "Setup MSYS2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-meson mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config mingw-w64-x86_64-ca-certificates mingw-w64-x86_64-shaderc
            mingw-w64-x86_64-curl mingw-w64-x86_64-cmake mingw-w64-x86_64-libyaml mingw-w64-x86_64-gperf
            mingw-w64-x86_64-itstool mingw-w64-x86_64-libxml2 mingw-w64-x86_64-docbook-xml
            mingw-w64-x86_64-docbook-xsl mingw-w64-x86_64-gettext mingw-w64-x86_64-vulkan-headers
            mingw-w64-x86_64-vulkan-loader mingw-w64-x86_64-rust mingw-w64-x86_64-python
            mingw-w64-x86_64-python-pip
      - name: "Download Dependency Sources"
        run: |
          git clone https://gitlab.gnome.org/GNOME/glib.git --depth 1
          git clone https://gitlab.freedesktop.org/cairo/cairo.git --depth 1
          git clone https://gitlab.gnome.org/GNOME/gobject-introspection.git --depth 1
          git clone https://gitlab.gnome.org/GNOME/pygobject.git --depth 1
          git clone https://github.com/ebassi/graphene.git --depth 1
          git clone https://github.com/GNOME/gdk-pixbuf.git --depth 1
          git clone https://github.com/GNOME/pango.git --depth 1
          git clone https://gitlab.gnome.org/GNOME/gtk.git --depth 1
          git clone https://github.com/ximion/appstream.git --branch v1.0.6 --depth 1
          git clone https://gitlab.gnome.org/GNOME/libadwaita.git --depth 1
          git clone https://gitlab.gnome.org/GNOME/blueprint-compiler.git --depth 1
      - name: Build Dependencies
        run: |
          build() {
            local name=$1
            local opts=$2
            echo "::group::Building $name"
            cd "$name"
            meson setup build --prefix=/mingw64 --reconfigure $opts
            meson install -C build
            cd ..
            echo "::endgroup::"
          }
          build "glib" "-Dtests=false -Dsysprof=disabled -Dintrospection=disabled"
          build "gobject-introspection" "-Dtests=false"
          build "pygobject" "-Dtests=false"
          build "glib" "-Dtests=false -Dsysprof=disabled -Dintrospection=enabled"
          build "cairo" "-Dtests=disabled"
          build "graphene" "-Dintrospection=enabled -Dtests=false"
          build "gdk-pixbuf" "-Dintrospection=enabled -Dtests=false -Dman=false"
          build "pango" "-Dintrospection=enabled"
          build "gtk" "-Dintrospection=enabled -Dmedia-gstreamer=disabled -Dbuild-tests=false -Dwin32-backend=true -Dvulkan=enabled -Dsysprof=disabled"
          build "appstream" "-Dsystemd=false -Dgir=true -Dstemming=false -Dzstd-support=false -Dapidocs=false -Dinstall-docs=false"
          build "libadwaita" "-Dintrospection=enabled -Dvapi=false -Ddocumentation=false -Dtests=false"
          build "blueprint-compiler" ""
      - name: Build Package
        run: |
          meson setup build -Dprefix=$(pwd)/dist -Dprofile=default
          meson install -C build
          ldd dist/bin/morse.exe | grep /mingw64/bin | cp $(awk '{print $3}') dist/bin
          cp /mingw64/bin/gdbus.exe dist/bin
          mkdir -p dist/lib/gdk-pixbuf-2.0
          cp -r /mingw64/lib/gdk-pixbuf-2.0/* dist/lib/gdk-pixbuf-2.0
      - name: Build Installer
        shell: powershell
        run: |
          iscc build-aux/morse_inno.iss
      - uses: actions/upload-artifact@v6
        with:
          name: Morse_Installer_x64_v${{ github.run_number }}
          path: Output/*.exe